config/routes.rb
Rails.application.routes.draw do

  resources :searchs
  resources :hospitals do
    resources :exams
  end
  resources :items

   root 'homepages#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items
  has_many :exam_lists
end

app/models/exam.rb
class Exam < ActiveRecord::Base
  belongs_to :hospital
  has_many :examlists
  has_many :categories, through: :examlists
  has_many :packages
  has_many :items, through: :packages
end

app/models/examlist.rb
class Examlist < ActiveRecord::Base
  belongs_to :exam
  belongs_to :category
end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
  has_many :exams
  belongs_to :location

  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :packages
  has_many :exams, through: :packages
  belongs_to :category
end

app/models/location.rb
class Location< ActiveRecord::Base
  has_many :hospitals

  def self.serch(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/models/package.rb
class Package < ActiveRecord::Base
  belongs_to :exam
  belongs_to :item
end

app/models/reserve.rb
class Reserve < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def okay
    render text: "hello, world!"
  end

end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  def index
    @hospital = Hospital.find(params[:hospital_id])
    @exams = @hospital.exams

   # @exams = Exam.where(hospital_id: params[:hospital])
   #@hospital = Hospital.first
   # @hospital = Hospital.find(params[:hospital])
  end
  def show
    @hospital = Hospital.find(params[:hospital_id])
    @exams = @hospital.exams
   #@exam = Exam.find(params[:id])
   #@examitem = @exams.items
  end

  def new
  end

  def create
  end
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController

  def index
    @locations = Location.all
    
    if params[:search]
      @hospitals = Hospital.search(params[:search])
    else
      @hospitals = Hospital.all
    end
  end

end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController

  def index
   # @location = Location.find(params[:location])
   # @hospitals = Hospital.where(location_id: params[:location])
    @categories = Category.all
    if params[:search]
      @hospitals = Hospital.search(params[:search])
    else
      @location = Location.find(params[:location])
      @hospitals = Hospital.where(location_id: params[:location])
    end
  end
end

app/controllers/reserves_controller.rb
class ExamsController < ApplicationController
  def index
  end

  def new
    @reserve = Reserve.new
  end

  def create
   # @reserve = Reseve.new(reserve_params)
   # if @reserve.save
   #   flash[:notice] = 
   # end
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController

  def index
    if params[:search]
      @hospitals = Hospital.search(params[:search])
    else
      @hospitals = Hospital.all
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/views/application/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p> RubyJJ 紅寶石健檢 ©
    <a > 聯絡RubyJJ </a>
    <a > 服務條款 </a>
    </p>
  </div>
</footer>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
      <%= image_tag ("ruby_plus.png") %>
      </a>
    </div>
  </div>
</nav>

app/views/exams/create.html.erb
<h1>Exams#create</h1>
<p>Find me in app/views/exams/create.html.erb</p>

app/views/exams/index.html.erb
<h1>
  <span class="glyphicon glyphicon-plus-sign"></span>
  <%= @hospital.name %>
</h1>
<p class="text-right">
  <span class="glyphicon glyphicon-circle-arrow-left"></span>
  <%= link_to '回到上一頁', :back %>
</p>
<div class="row">
<% @exams.each do |exam| %>
  <div class="col-md-4">
    <div class="exam_list">
      <table class="table">
        <thead>
          <tr>
           <td width="46px"> <%= image_tag("doc_plus.png") %></td>
            <td> <%= exam.name %> </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>性別</td>
            <td><%= exam.gender %></td>
          </tr>
          <tr>
            <td>費用</td>
            <td><%= number_to_currency exam.price %></td>
          </tr>
          <tr>
            <td>健檢
            </td>
            <td>
              <%= content_tag :a,data: {toggle: "modal", target: "\#m#{exam.id}"} do %>
                項目清單
                  共 <%= exam.items.count %> 項
                <span class="glyphicon glyphicon-modal-window" aria-hidden="true" style="color:#d26e5c"></span>
              <% end %>
              <%= content_tag :div,id:"m#{exam.id}", tabindex:"-1", role:"dialog",aria: {labelledby:"m#{exam.id}Label", hidden:"true"} , class:"modal fade" do %>
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-label="close"><span aria-hidden="true">&times;</span></button>
                      <h2>
                      <span class="glyphicon glyphicon-file"></span>
                      <%= exam.name %>
                      </h2>
                    </div>
                    <div class="modal-body">
                      <span class="glyphicon glyphicon-list-alt"></span>
                      健檢項目：共 <%= exam.items.count %> 項
                      <% exam.categories.each do |category| %>
                        <div class="row">
                          <div class="col-md-12">
                            <h3><%= category.name %></h3>
                          </div>
                          <% exam.items.where(category_id: "#{category.id}").each do |item| %>
                          <div class="col-xs-6 col-sm-6 col-md-6">
                            <li><%= item.name %></li>
                          </div>
                          <% end %>
                        </div>
                      <% end %>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                  </div>
                </div>
              <% end %>
            </td>
          </tr>
          <!--
          <tr>
            <td colspan="2" style="text-align:center">
              <% content_tag :button,'我要預約', class:"btn btn-success", data: {toggle: "modal", target:"\#m#{exam.id}"}, style: "width:100%" %>
            </td>
          </tr>
          -->
        </tbody>
      </table>
    </div>
  </div>
<% end %>
</div>

app/views/exams/new.html.erb
<h1>Exams#new</h1>
<p>Find me in app/views/exams/new.html.erb</p>

app/views/exams/show.html.erb
  套餐名：
<% @exams.each do |exam| %>
  <%= exam.name %>
  <%= exam.price %>
  <%= exam.gender %>
  <%= exam.description %>
<% end %>
  <br>
  項目：

app/views/homepages/index.html.erb
<div class="row">
  <div class="col-md-5 text-center col-md-offset-1 location">
    <%= image_tag("locations.png") %>
    <br/>
    <h1>
      台灣健康檢查比較台
    </h1>
  </div>
  <div class="col-md-5 location_search">
    <div class="row">
      <div class="col-md-12 ">
        <%= form_tag searchs_path, :method => 'get' do %>
          <%= text_field_tag :search, params[:search], placeholder:'輸入關鍵字', class:'form-control', style: 'width: 100%; height: 44px' %>
          <br/>
          <%= submit_tag "全 站 搜 尋", :name => nil, class:'btn btn-success', style: 'width: 100%; height: 44px' %>
        <% end %>
      <br/>
      </div>
      <% @locations.each do |location| %>
        <div class="col-xs-6 col-sm-4 col-md-4">
          <%= link_to location.name, hospitals_path(location: location), class: 'location_tag' %>
          <%= content_tag :span, class:'badge' do %>
            <%= location.hospitals.count %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/hospitals/index.html.erb
<h1>
  <span class="glyphicon glyphicon-map-marker"></span>
  <%= @location.name %> 健康檢查服務醫院
</h1>
<p class="text-right">
   <span class="glyphicon glyphicon-circle-arrow-left"></span>
     <%= link_to '回到上一頁', '/' %>
</p>
<div class="row card">
<% @hospitals.each do |hospital| %>
  <div class="col-sm-6 col-md-4 col-lg-3">
    <div class="hospital_list">
      <table class="table">
        <thead>
          <tr>
            <td> <%= image_tag("ruby_plus.png") %></td>
            <td> <%= hospital.name %> </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>地址</td>
            <td><%= hospital.address %></td>
          </tr>
          <tr>
            <td>電話</td>
            <td><%= hospital.phone %></td>
          </tr>
          <tr>
            <td>網站</td>
            <td><%= link_to '進入網站', hospital.web, target:"_blank" %></td>
          </tr>
          <tr>
            <td>健檢
            </td>
            <td>熱門套餐
              <ul>
              <% hospital.exams.order("random()").limit(3).each do |exam| %>
                <li>
                <%= content_tag :a, data: {toggle: "modal", target:"\#m#{exam.id}"} do %>
                  <%= exam.name[0..11] %>
                  <span class="glyphicon glyphicon-collapse-down" aria-hidden="true" style="color:#d26e5c"></span>
                <% end %>
                </li>
                <%= content_tag :div, id: "m#{exam.id}", tabindex:"-1", role: "dialog", aria: { labelledby: "m#{exam.id}Label", hidden: "true"}, class:"modal fade" do %>
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="close"><span aria-hidden="true">&times;</span></button>
                        <h2>
                          <%= image_tag("doc_plus.png") %>
                          <%= exam.name %>
                        </h2>
                      </div>
                      <div class="modal-header">
                        <div class="exam-detail">
                          <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                              <span class="glyphicon glyphicon-plus-sign"></span>
                              <%= hospital.name %>
                            </div>
                          </div >
                        </div>
                      </div>
                      <div class="modal-header">
                          <div class="row">
                        <div class="exam-detail">
                            <div class="col-xs-6 col-sm-6 col-md-6">
                              <span class="glyphicon glyphicon-credit-card"></span>
                              費用： <%= number_to_currency exam.price %>
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-6">
                              <span class="glyphicon glyphicon-user"></span>
                              性別：<%= exam.gender %>
                            </div>
                          </div >
                        </div>
                      </div>
                      <div class="modal-body">
                        <span class="glyphicon glyphicon-list-alt"></span>
                        健檢項目：共 <%= exam.items.count %> 項
                        <% exam.categories.each do |category| %>
                          <div class="row">
                            <div class="col-md-12">
                              <h3>
                                <%= category.name %>
                              </h3>
                            </div>
                            <% exam.items.where(category_id: "#{category.id}").each do |item| %>
                              <div class="col-md-6">
                                <li><%= item.name %></li>
                              </div>
                            <% end %>
                          </div>
                        <% end %>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% end %>
                <li><%= link_to '查看更多',hospital_exams_path(hospital.id), class:'' %>
                  <span class="glyphicon glyphicon-collapse-down" aria-hidden="true" style="color:#d26e5c"></span>
                </li>
              </ul>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Humandock</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'navbar' %>
  <div class="container">
    <%= yield %>
  </div>

  <%= render 'footer' %>
</body>
</html>

app/views/searchs/_hospitals_search.html.erb
<h1>
  搜尋結果：
</h1>
<p class="text-right">
   <span class="glyphicon glyphicon-circle-arrow-left"></span>
     <%= link_to '回到上一頁', :back %>
</p>
<div class="row">
<% @hospitals.each do |hospital| %>
  <div class="col-md-4">
    <div class="hospital_list">
      <table class="table">
        <thead>
          <tr>
            <td> <%= image_tag("ruby_plus.png") %></td>
            <td> <%= hospital.name %> </td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>地址</td>
            <td><%= hospital.address %></td>
          </tr>
          <tr>
            <td>電話</td>
            <td><%= hospital.phone %></td>
          </tr>
          <tr>
            <td>網站</td>
            <td><%= link_to '進入網站', hospital.web %></td>
          </tr>
          <tr>
            <td>健檢
            </td>
            </td>
            <td>熱門套餐
              <ul>
              <% hospital.exams.order("random()").limit(5).each do |exam| %>
                <li>
                <%= content_tag :a, data: {toggle: "modal", target:"\#m#{exam.id}"} do %>
                  <%= exam.name %>
                  <span class="glyphicon glyphicon-collapse-down" aria-hidden="true" style="color:#d26e5c"></span>
                <% end %>
                </li>
                <%= content_tag :div, id: "m#{exam.id}", tabindex:"-1", role: "dialog", aria: { labelledby: "m#{exam.id}Label", hidden: "true"}, class:"modal fade" do %>
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="close"><span aria-hidden="true">&times;</span></button>
                        <h2>
                        <%= image_tag("doc_plus.png") %>
                          <%= exam.name %>
                        </h2>
                      </div>
                      <div class="modal-header">
                        <div class="exam-detail">
                          <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                              <span class="glyphicon glyphicon-plus-sign"></span>
                              <%= hospital.name %>
                            </div>
                          </div >
                        </div>
                      </div>
                      <div class="modal-header">
                        <div class="exam-detail">
                          <div class="row">
                            <div class="col-xs-6 col-sm-6 col-md-6">
                              <span class="glyphicon glyphicon-credit-card"></span>
                              費用： <%= number_to_currency exam.price %>
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-6">
                              <span class="glyphicon glyphicon-user"></span>
                              性別：<%= exam.gender %>
                            </div>
                          </div >
                        </div>
                      </div>
                      <div class="modal-body">
                        <span class="glyphicon glyphicon-list-alt"></span>
                        健檢項目：共 <%= exam.items.count %> 項
                        <% exam.categories.each do |category| %>
                          <div class="row">
                            <div class="col-md-12">
                              <h3>
                              <%= category.name %>
                              </h3>
                            </div>
                          <% category.items.each do |item| %>
                            <div class="col-md-6">
                              <li><%= item.name %></li>
                            </div>
                          <% end %>
                          </div>
                        <% end %>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% end %>
              <%= link_to '查看更多',exams_path(hospital: hospital), class:'btn btn-success' %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
<% end %>
</div>

app/views/searchs/index.html.erb
<%= render 'hospitals_search' %>